server:
  port: 8000
spring:
  redis:
    port: 6379
    host: 192.168.188.128
  application:
    name: SCW-PROJECT
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/offcn/scwproject/mapper/*.xml
logging:
  file:
    path: F:\log\scw-project
  level:
    com:
      offcn: debug
oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5tNr98uaA34CTD59Bmk8
  accessKeySecret: PQmdX47izS03eRcLFW4LNfQvQCOfi4
  bucketName: hunter2021